### ISSUE TITLE
TTS inference error

### ISSUE THREAD

**Issue by rikabi89** [MWM-io/nansypp#3]
Win11 WSL Anaconda ENV 3.9

Trying to run inference using the pre-trained models and I get this error : 

https://justpaste.it/fx6ye <--- Error is too long to post here, here is the full script.

Here is a snippet :  

```
InstantiationException: Error in call to target 'src.networks.backbone.encoders.wav2vec2.Wav2Vec2Wrapper':
OSError("We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like facebook/wav2vec2-large-xlsr-53 is not the path to a directory containing a file named config.json.\nCheckout
your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.")
full_key: network.style_encoder.wav2vec2
(nansypp) root@DESKTOP-G461NBO:/mnt/h/nansypp#
```

**Comment by KaluginD** [comment]
Hi @rikabi89 , thank you for reporting the issue. It should be fixed by the [new commit](https://github.com/MWM-io/nansypp/commit/bbc6e390632bad56d5c0764074390a9f4a23fb86). 
As the linguistic encoder module uses the wav2vec2 model from HuggingFace, it was expected to have the ["facebook/wav2vec2-large-xlsr-53"](https://huggingface.co/facebook/wav2vec2-large-xlsr-53) model pre-downloaded on your machine (`local_files_only=True` flag). It is no longer the case.
Please pull the last commit and try again.
